### ISSUE TITLE
Support for source maps

### ISSUE THREAD

**Issue by ahanriat** [samblake/react-native-typescript-starter-2017#1]
Hi guys !

Do you have any idea how to enable the source maps when debugging in chrome ?

**Comment by samblake** [comment]
Did you try setting sourceMap to true in tsconfig.json? That will generate the source maps for you.

**Comment by ahanriat** [comment]
Yes and then I have the following error:
![screen shot 2017-05-05 at 09 58 24](https://cloud.githubusercontent.com/assets/1374161/25737690/778a2810-3179-11e7-8732-c2b9f9e1dd60.png)

Did you managed to get the source maps working?

**Comment by llaine** [comment]
Experiencing the same issue, source maps are generated but not able to launch the app.
![capture d ecran de 2017-05-05 11-30-30](https://cloud.githubusercontent.com/assets/3087812/25740312/4986a936-3186-11e7-8cf3-d55e1edae31e.png)

**Comment by samblake** [comment]
Hi @ahanriat, the workaround for that issue is described at #https://github.com/mhzed/react-native-sm-transformer/issues/3

**Comment by samblake** [comment]
Hi @llaine, that looks like a different issue. It looks like you're using a newer version of react-native. See the open issue #https://github.com/mhzed/react-native-sm-transformer/issues/2

**Comment by samblake** [comment]
I've downgraded the react-native version to 0.41.2. Run `rm -rf node_modules && yarn` and you should be able to deploy with source maps afterwards.
